# Generated by Django 5.1.3 on 2024-11-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='AGE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='DEPARTMENT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='EMAILID',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='MOBILE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='PLACE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
