# Generated by Django 5.1.3 on 2024-11-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0002_studentdb_age_studentdb_department_studentdb_emailid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentdb',
            new_name='Employeedb',
        ),
    ]
