# Generated by Django 5.1.3 on 2024-11-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0004_alter_employeedb_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedb',
            name='PLACE',
        ),
    ]
